//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFChatBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1	�ӹ��� ������
        ///2	�ӹ��� �繰 ����
        ///3	���� ����
        ///4	Ż��
        ///5	�ڷ���
        ///6	����
        ///7	����
        ///8	���
        ///9	����� �˰�
        ///10	ö�� ���
        ///11	�߼��� �˰�
        ///12	��Ȱ
        ///13	�氢��
        ///14	�÷���
        ///15	������ �˰�
        ///16	���� ����
        ///17	���
        ///18	����
        ///19	��ö�� ����
        ///20	��������
        ///21	�ҷγ��� �г�
        ///22	���� ����
        ///23	�ĸ��� ��
        ///24	���� ������
        ///25	���� �ķ�ġ��
        ///26	������ ��
        ///27	���α�
        ///28	������ ����
        ///29	������ �ⰳ
        ///30	õ�Ϲ���
        ///31	������ �ϰ�
        ///32	������
        ///33	����
        ///34	���� ����
        ///35	�ΰ��� ����
        ///36	������ �ϰ�
        ///37	���� �ı�
        ///38	����ȭ
        ///39	��Ȥ�� �ϰ�
        ///40	������ ¥����
        ///41	�е�
        ///42	��ǳ [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string action_exh_ko {
            get {
                return ResourceManager.GetString("action_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2	��ȯ
        ///3	���󰡱�
        ///4	���� ����
        ///5	��� �¼�
        ///6	���� �¼�
        ///7	ȸ�� �¼�
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buddyaction_exh_ko {
            get {
                return ResourceManager.GetString("buddyaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0	���谡
        ///1	�˼���
        ///2	������
        ///3	��������
        ///4	â����
        ///5	�ü���
        ///6	ȯ����
        ///7	�ּ���
        ///8	���
        ///9	��������
        ///10	�������ۻ�
        ///11	����������
        ///12	���װ�����
        ///13	�����
        ///14	���ݼ���
        ///15	�丮��
        ///16	����
        ///17	������
        ///18	���
        ///19	����Ʈ
        ///20	��ũ
        ///21	����
        ///22	����
        ///23	��������
        ///24	�鸶����
        ///25	�渶����
        ///26	�����
        ///27	��ȯ��
        ///28	����
        ///29	�ְ˻�
        ///30	����
        ///31	�����
        ///32	������
        ///33	��������
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string classjob_exh_ko {
            get {
                return ResourceManager.GetString("classjob_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	���� ��
        ///2	�ڵ�����001
        ///3	�������ں�
        ///4	ĳƮ�� ����
        ///5	���̺��
        ///6	�ڵ�����003L
        ///7	�ڵ�����003G
        ///8	�ڵ�����003U
        ///9	��ʹ� �������ں�
        ///10	�ֻ�� �������ں�
        ///11	�Ҹ�� �������ں�
        ///12	��� ����
        ///13	���� û����
        ///14	�ּ��̹���
        ///15	������ ����
        ///16	�Ķ���
        ///17	���� ����
        ///18	�Ʊ� ����
        ///19	���� Ŀ��
        ///20	���� Ŀ��
        ///21	���� ����
        ///22	�ڰ� ��
        ///23	�溣�� ����
        ///24	���� �ݰ��ź�
        ///25	�Ʊ� ���丣
        ///26	�Ʊ� ����
        ///27	���� ����
        ///28	�����䳢
        ///29	����� ����
        ///30	�տ�ì��
        ///31	����Ǫũ
        ///32	���� ����
        ///33	�̴��ٴ�
        ///34	�Ʊ� ��
        ///35	�Ʊ� ����
        ///36	���� ����
        ///37	���� ����
        ///38	�ں�� ��[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string companion_exh_ko {
            get {
                return ResourceManager.GetString("companion_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   101	상용구 사전을 사용해주세요.
        ///102	일본어
        ///103	영어
        ///104	프랑스어
        ///105	독일어
        ///106	일본어로 대화해도 될까요?
        ///107	영어로 대화해도 될까요?
        ///108	프랑스어로 대화해도 될까요?
        ///109	독일어로 대화해도 될까요?
        ///110	저는 영어를 못합니다.
        ///111	저는 일본어를 못합니다.
        ///112	저는 프랑스어를 못합니다.
        ///113	저는 독일어를 못합니다.
        ///114	제 말을 들어주세요.
        ///115	들리십니까?
        ///116	간단한 의사소통은 가능합니다.
        ///117	조금은 이해할 수 있습니다.
        ///118	쉬운 단어로 말씀해주세요.
        ///119	줄임말은 사용하지 말아주세요.
        ///120	곧 대답하겠습니다, 잠시만 기다려주세요.
        ///121	모국어는 무엇입니까?
        ///200	【인사】
        ///201	처음 뵙겠습니다.
        ///202	좋은 아침입니다!
        ///203	안녕하세요.
        ///204	오늘 하루 어떠셨나요?
        ///205	안녕히 주무세요.
        ///206	좋은 하루 보내세요.
        ///207	재미있었어요.
        ///208	또 만나요!
        ///209	또 같이 놀아요.[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string completion_exh_ko {
            get {
                return ResourceManager.GetString("completion_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100001	작업
        ///100002	가공
        ///100003	능숙한 땜질
        ///100004	중급 가공
        ///100005	능숙한 땜질 2
        ///100006	바람의 인장
        ///100007	중급 작업
        ///100008	고급 가공
        ///100009	비레고의 축복
        ///100010	경과 관찰
        ///100015	작업
        ///100016	가공
        ///100017	능숙한 땜질
        ///100018	중급 가공
        ///100019	능숙한 땜질 2
        ///100020	불의 인장
        ///100021	중급 작업
        ///100022	고급 가공
        ///100023	경과 관찰
        ///100030	작업
        ///100031	가공
        ///100032	능숙한 땜질
        ///100033	강행 작업
        ///100034	중급 가공
        ///100035	능숙한 땜질 2
        ///100036	얼음의 인장
        ///100037	중급 작업
        ///100038	고급 가공
        ///100039	꾸준한 진척
        ///100040	경과 관찰
        ///100045	작업
        ///100046	가공
        ///100047	능숙한 땜질
        ///100048	중급 가공
        ///100049	능숙한 땜질 2
        ///100050	땅의 인장
        ///100051	중급 작[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string craftaction_exh_ko {
            get {
                return ResourceManager.GetString("craftaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	�ڵ� ����
        ///2	����
        ///3	����Ʈ �극��ũ
        ///4	���� ����
        ///5	����
        ///6	����
        ///7	�ڷ���
        ///8	����
        ///9	Ż�� ������ ȣ��
        ///10	���� ģ�� ������ ȣ��
        ///12	���׸��� ����
        ///13	���׸��� ���� 2
        ///14	���׸���ȭ
        ///15	����
        ///16	����: �������
        ///17	����: ��������
        ///18	��ġ
        ///19	���� �ص�
        ///20	Ž��
        ///21	����
        ///22	��� ����
        ///23	������
        ///24	���� Ż�� ������ ȣ��
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string generalaction_exh_ko {
            get {
                return ResourceManager.GetString("generalaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	�ҷγ�
        ///2	�޴��ǳ�
        ///3	�츮��ũ
        ///4	�ϸ��̾�
        ///5	���ɷ�
        ///6	������
        ///7	�񷹰�
        ///8	����
        ///9	������
        ///10	����
        ///11	����ī
        ///12	�˵�ũ
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string guardiandeity_exh_ko {
            get {
                return ResourceManager.GetString("guardiandeity_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	@
        ///2	@
        ///3	@
        ///4	@
        ///5	@
        ///6	@
        ///7	@
        ///8	@
        ///9	@
        ///10	@
        ///11	@
        ///13	@
        ///14	@
        ///15	@
        ///16	@
        ///17	@
        ///18	@
        ///19	@
        ///20	@
        ///22	@
        ///23	@
        ///24	@
        ///25	@
        ///49	mount
        ///50	classjob
        ///51	placename
        ///52	race
        ///53	tribe
        ///54	guardiandeity
        ///55	generalaction
        ///56	action
        ///57	craftaction
        ///58	buddyaction
        ///59	petaction
        ///60	weather
        ///61	maincommand
        ///62	textcommand
        ///63	action
        ///64	pet
        ///65	companion
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0	
        ///1	무기 넣기/꺼내기
        ///2	내 캐릭터
        ///3	기술 목록
        ///4	퀘스트
        ///5	임무 정보 목록
        ///6	업적 목록
        ///7	채집수첩
        ///8	토벌수첩
        ///9	제작수첩
        ///10	소지품
        ///11	임무용 아이템 목록
        ///12	파티원
        ///13	친구 목록 관리
        ///14	차단 목록 관리
        ///15	플레이어 검색
        ///16	지도
        ///17	감정 표현
        ///18	대상 표식
        ///19	시스템 설정
        ///20	단축키 설정
        ///21	매크로 관리
        ///22	HUD 배열 변경
        ///23	접속 종료
        ///24	게임 종료
        ///25	장비함
        ///26	
        ///27	자유부대
        ///28	링크셸
        ///29	낚시수첩
        ///30	도움말
        ///31	추천 임무
        ///32	
        ///33	임무 찾기
        ///34	캐릭터 설정
        ///35	텔레포
        ///36	데존
        ///37	등급 및 라이선스 표시
        ///38	수첩
        ///39	플레이어 간 교류
        ///40	시스템
        ///41	어류도감
        ///42	버디
        ///43	임무
        ///44	하우징
        ///45	화면 설정
        ///46	소리 설정
        ///47	그래픽 설정
        ///48	마우스 설정
        ///49	&lt;if(PLYR: 76 ? 1 ) {컨트롤러 설정} else {게임패드 설정[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string maincommand_exh_ko {
            get {
                return ResourceManager.GetString("maincommand_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	�� ���ں�
        ///4	����
        ///5	���Ž� ���ں�
        ///6	���� �Ƹ�
        ///8	Ŀ��
        ///9	�Ƹ���
        ///15	������
        ///18	������
        ///19	�Ʒõ� ������
        ///20	����� ����
        ///21	C�� ���� �Ƹ�
        ///22	����Ʈ�޾�
        ///25	�׺� ���ں�
        ///26	�Ʒõ� ���꽺Ʈ
        ///27	�� ����
        ///28	������
        ///29	ũ���佺
        ///30	���Ž�
        ///31	���ٸ�
        ///32	��������
        ///33	������
        ///34	�׶����ں�
        ///35	���̾����
        ///36	���� �ιλ� ����
        ///37	�׸��ٴϾ� ����
        ///38	����� ����
        ///40	����ī��
        ///41	�������ں�
        ///42	���������ϸ�
        ///43	�����ƽ�
        ///44	������ ���ں�
        ///45	���� ���ں�
        ///46	�ݰ��ź�
        ///47	�⸰
        ///48	ž�� �ý���
        ///49	�渮��
        ///50	�̵尡�������
        ///52	���� �׶����ں�
        ///53	�紩��
        ///54	�׸���
        ///55	�[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mount_exh_ko {
            get {
                return ResourceManager.GetString("mount_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	ī��Ŭ ���޶���
        ///2	ī��Ŭ ������
        ///3	������Ʈ ����
        ///4	Ÿ��ź ����
        ///5	����� ����
        ///6	���� ������
        ///7	���� ������
        ///8	�ڵ���ž ��
        ///9	�ڵ���ž ���
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pet_exh_ko {
            get {
                return ResourceManager.GetString("pet_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	��ȯ
        ///2	����
        ///3	�̵�
        ///4	���
        ///5	����
        ///6	��ȭ
        ///7	���� ����
        ///8	���� ����
        ///9	��ǳ
        ///10	������
        ///11	�ϰ� ���
        ///12	���޶����� ����
        ///13	������
        ///14	�������� ��
        ///15	��ũ����
        ///16	���� ��ġ��
        ///17	�ٶ��� Į��
        ///18	�����
        ///19	��� ������
        ///20	��ȭ
        ///21	��� ����
        ///22	���� �ɰ���
        ///23	�� �ɰ���
        ///24	������ ��ȣ
        ///25	�����
        ///26	������ �г�
        ///27	��ȫ ȸ����
        ///28	��Ÿ�� �ϰ�
        ///29	������ ����
        ///30	ȭ�� �ۿ�
        ///31	������ ȭ��
        ///32	���� ġ��
        ///33	���� �ӻ���
        ///34	������ ����
        ///35	������ ����
        ///36	���� ġ��
        ///37	���� ħ��
        ///38	������ �ձ�
        ///39	������ �ٶ�
        ///40	���� ����
        ///41	���� ��[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string petaction_exh_ko {
            get {
                return ResourceManager.GetString("petaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   18	��� �Ƿ�
        ///20	���̵���
        ///21	����������
        ///22	���þ�
        ///23	�����帷 ��
        ///24	�ٳ���
        ///25	Ŀ���ٽ�
        ///26	�𸣵���
        ///27	���� �ιλ�
        ///28	���� �ιλ� ���� ����
        ///29	���� �ιλ� ���� ����
        ///30	�ߺ� ���þ�
        ///31	���� ���þ�
        ///32	���� ���þ�
        ///33	���� ���þ�
        ///34	���� ���þ�
        ///35	�罺Ÿ�� ħ�� ����
        ///36	�극���÷Ͻ��� �߿���
        ///37	������� ����
        ///39	�׸��ٴϾ�
        ///40	����� �� ȸ��
        ///41	����� �� ȸ��
        ///42	���� �ٳ���
        ///43	�ߺ� �ٳ���
        ///44	���� �ٳ���
        ///45	���� �ٳ���
        ///46	�Ϻ� �ٳ���
        ///47	�������� ���
        ///48	������ ����
        ///49	�Ҷ�Ż�� ������
        ///50	ī���� ������ ���
        ///51	�����
        ///52	�׸��ٴϾ� �Žð���
        ///53	�[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string placename_exh_ko {
            get {
                return ResourceManager.GetString("placename_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	�޷�
        ///2	������
        ///3	�����
        ///4	������
        ///5	�簡��
        ///6	�ƿ��
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string race_exh_ko {
            get {
                return ResourceManager.GetString("race_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   102	/말
        ///103	/외
        ///104	/귓
        ///105	/파
        ///106	/링
        ///107	/링1
        ///108	/링2
        ///109	/링3
        ///110	/링4
        ///111	/링5
        ///112	/링6
        ///113	/링7
        ///114	/링8
        ///115	/자
        ///116	/혼
        ///117	/떠
        ///118	/대답
        ///119	/연
        ///121	/참가
        ///122	/거절
        ///123	/초대
        ///124	/추방
        ///125	/파티장
        ///126	/탈퇴
        ///131	/조사
        ///132	/거래
        ///133	/자동달리기
        ///134	/따라가기
        ///135	/전리품
        ///136	/마테리아요청
        ///141	/캐릭터
        ///142	/퀘스트
        ///143	/임무찾기
        ///144	/장비함
        ///145	/토벌수첩
        ///146	/제작수첩
        ///147	/채집수첩
        ///148	/낚시수첩
        ///149	/업적
        ///150	/파티명령
        ///151	/친구목록
        ///152	/차단목록
        ///153	/플레이어검색
        ///154	/지도
        ///155	/텔레포
        ///156	/표식지정
        ///157	/기술목록
        ///158	/임무대기
        ///159	/추천임무
        ///160	/소지품
        ///161	/자유부대명령
        ///162	/링크셸명령
        ///16[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textcommand_exh_ko {
            get {
                return ResourceManager.GetString("textcommand_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	�߿� ����
        ///2	��� ����
        ///3	�� ����
        ///4	Ȳȥ ����
        ///5	��� ����
        ///6	�縷 ����
        ///7	�¾��� ������
        ///8	���� ��ȣ��
        ///9	�ٴٴ���
        ///10	�Ҳ���Ŵ��
        ///11	�ƿ�� ��
        ///12	�ƿ�� ����
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tribe_exh_ko {
            get {
                return ResourceManager.GetString("tribe_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	��û
        ///2	����
        ///3	�帲
        ///4	�Ȱ�
        ///5	�ٶ�
        ///6	��ǳ
        ///7	��
        ///8	����
        ///9	����
        ///10	����
        ///11	�𷡸���
        ///12	����ǳ
        ///13	����
        ///14	�ۿ���
        ///15	��
        ///16	������
        ///17	�丶�� �Ȱ�
        ///18	���ζ�
        ///19	���
        ///20	����
        ///21	�帲
        ///22	����
        ///23	�Ķ�
        ///24	�Ķ�
        ///25	�Ա���
        ///26	�ۿ���
        ///27	�丶�� �Ȱ�
        ///28	��ǳ
        ///29	��ȭ
        ///30	����
        ///31	����
        ///32	����
        ///33	����
        ///34	����
        ///35	�ر�
        ///36	����
        ///37	����
        ///38	����
        ///39	����
        ///40	������
        ///41	������
        ///42	������
        ///43	������
        ///44	����
        ///45	����
        ///46	����
        ///47	����
        ///48	����
        ///49	�׸��ڹٶ�
        ///50	����
        ///51	����
        ///52	����
        ///53	�߼�����
        ///54	�����ĵ�
        ///55	�߼�����
        ///56	����[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string weather_exh_ko {
            get {
                return ResourceManager.GetString("weather_exh_ko", resourceCulture);
            }
        }
    }
}
