//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFChatBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1	임무용 아이템
        ///2	임무용 사물 조작
        ///3	전력 질주
        ///4	탈것
        ///5	텔레포
        ///6	데존
        ///7	공격
        ///8	사격
        ///9	재빠른 검격
        ///10	철벽 방어
        ///11	야성의 검격
        ///12	재활
        ///13	경각심
        ///14	플래시
        ///15	폭도의 검격
        ///16	방패 가격
        ///17	경계
        ///18	도발
        ///19	강철의 의지
        ///20	임전무퇴
        ///21	할로네의 분노
        ///22	방패 각성
        ///23	파멸의 진
        ///24	방패 던지기
        ///25	방패 후려치기
        ///26	충의의 검
        ///27	감싸기
        ///28	충의의 방패
        ///29	내면의 기개
        ///30	천하무적
        ///31	육중한 일격
        ///32	예지력
        ///33	골절
        ///34	피의 갈증
        ///35	두개골 절단
        ///36	최후의 일격
        ///37	관절 파괴
        ///38	광폭화
        ///39	잔혹한 일격
        ///40	전투의 짜릿함
        ///41	압도
        ///42	폭풍 쐐기
        ///43	일대일 결투
        ///44	보복
        ///45	폭풍의 눈
        ///46	도끼 던지기
        ///47	휘도는 도끼
        ///48	수비 태세
        ///49	원초의 혼
        ///50	힘의 해방
        ///51	강철 회오리
        ///52	전장의 함성
        ///53	연격
        ///54	정권 지르기        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string action_exh_ko {
            get {
                return ResourceManager.GetString("action_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2	귀환
        ///3	따라가기
        ///4	자유 전투
        ///5	방어 태세
        ///6	공격 태세
        ///7	회복 태세
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string buddyaction_exh_ko {
            get {
                return ResourceManager.GetString("buddyaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0	모험가
        ///1	검술사
        ///2	격투사
        ///3	도끼술사
        ///4	창술사
        ///5	궁술사
        ///6	환술사
        ///7	주술사
        ///8	목수
        ///9	대장장이
        ///10	갑주제작사
        ///11	보석공예가
        ///12	가죽공예가
        ///13	재봉사
        ///14	연금술사
        ///15	요리사
        ///16	광부
        ///17	원예가
        ///18	어부
        ///19	나이트
        ///20	몽크
        ///21	전사
        ///22	용기사
        ///23	음유시인
        ///24	백마도사
        ///25	흑마도사
        ///26	비술사
        ///27	소환사
        ///28	학자
        ///29	쌍검사
        ///30	닌자
        ///31	기공사
        ///32	암흑기사
        ///33	점성술사
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string classjob_exh_ko {
            get {
                return ResourceManager.GetString("classjob_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	꼬마 봄
        ///2	자동인형001
        ///3	초코초코보
        ///4	캐트시 인형
        ///5	베이비모스
        ///6	자동인형003L
        ///7	자동인형003G
        ///8	자동인형003U
        ///9	흑와단 초코초코보
        ///10	쌍사당 초코초코보
        ///11	불멸대 초코초코보
        ///12	몰볼 묘목
        ///13	꼬마 청설모
        ///14	애송이버섯
        ///15	벼룩모기 유충
        ///16	파랑새
        ///17	꼬마 영양
        ///18	아기 임프
        ///19	꼬마 커얼
        ///20	검은 커얼
        ///21	힐디 인형
        ///22	자갈 골렘
        ///23	톤베리 인형
        ///24	꼬마 금강거북
        ///25	아기 랍토르
        ///26	아기 박쥐
        ///27	꼬마 묘목
        ///28	먼지토끼
        ///29	듈라한 인형
        ///30	왕올챙이
        ///31	통통푸크
        ///32	꼬마 물소
        ///33	미니텐더
        ///34	아기 게
        ///35	아기 늑대
        ///36	꼬마 눈알
        ///37	꼬마 도도
        ///38	코브란 유충
        ///39	큰뿔염소 인형
        ///40	꼬마 아프칼루
        ///41	새싹 구부
        ///42	미니 푸딩
        ///43	마도 뱅가드 추종형
        ///44	악마의 벽돌
        ///45	작은 두더지
        ///46	꼬마 양
        ///47	작은 슬라임
        ///48	작은 만드라고라
        ///49[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string companion_exh_ko {
            get {
                return ResourceManager.GetString("companion_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   101	상용구 사전을 사용해주세요.
        ///102	일본어
        ///103	영어
        ///104	프랑스어
        ///105	독일어
        ///106	일본어로 대화해도 될까요?
        ///107	영어로 대화해도 될까요?
        ///108	프랑스어로 대화해도 될까요?
        ///109	독일어로 대화해도 될까요?
        ///110	저는 영어를 못합니다.
        ///111	저는 일본어를 못합니다.
        ///112	저는 프랑스어를 못합니다.
        ///113	저는 독일어를 못합니다.
        ///114	제 말을 들어주세요.
        ///115	들리십니까?
        ///116	간단한 의사소통은 가능합니다.
        ///117	조금은 이해할 수 있습니다.
        ///118	쉬운 단어로 말씀해주세요.
        ///119	줄임말은 사용하지 말아주세요.
        ///120	&quot;곧 대답하겠습니다, 잠시만 기다려주세요.&quot;
        ///121	모국어는 무엇입니까?
        ///200	【인사】
        ///201	처음 뵙겠습니다.
        ///202	좋은 아침입니다!
        ///203	안녕하세요.
        ///204	오늘 하루 어떠셨나요?
        ///205	안녕히 주무세요.
        ///206	좋은 하루 보내세요.
        ///207	재미있었어요.
        ///208	또 만나요!
        ///209	또 같이 놀아[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string completion_exh_ko {
            get {
                return ResourceManager.GetString("completion_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100001	작업
        ///100002	가공
        ///100003	능숙한 땜질
        ///100004	중급 가공
        ///100005	능숙한 땜질 2
        ///100006	바람의 인장
        ///100007	중급 작업
        ///100008	고급 가공
        ///100009	비레고의 축복
        ///100010	경과 관찰
        ///100015	작업
        ///100016	가공
        ///100017	능숙한 땜질
        ///100018	중급 가공
        ///100019	능숙한 땜질 2
        ///100020	불의 인장
        ///100021	중급 작업
        ///100022	고급 가공
        ///100023	경과 관찰
        ///100030	작업
        ///100031	가공
        ///100032	능숙한 땜질
        ///100033	강행 작업
        ///100034	중급 가공
        ///100035	능숙한 땜질 2
        ///100036	얼음의 인장
        ///100037	중급 작업
        ///100038	고급 가공
        ///100039	꾸준한 진척
        ///100040	경과 관찰
        ///100045	작업
        ///100046	가공
        ///100047	능숙한 땜질
        ///100048	중급 가공
        ///100049	능숙한 땜질 2
        ///100050	땅의 인장
        ///100051	중급 작[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string craftaction_exh_ko {
            get {
                return ResourceManager.GetString("craftaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	자동 공격
        ///2	점프
        ///3	리미트 브레이크
        ///4	전력 질주
        ///5	분해
        ///6	수리
        ///7	텔레포
        ///8	데존
        ///9	탈것 무작위 호출
        ///10	꼬마 친구 무작위 호출
        ///12	마테리아 장착
        ///13	마테리아 장착 2
        ///14	마테리아화
        ///15	염색
        ///16	조준: 순서대로
        ///17	조준: 역순으로
        ///18	설치
        ///19	지도 해독
        ///20	탐색
        ///21	정제
        ///22	장비 투영
        ///23	내리기
        ///24	나는 탈것 무작위 호출
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string generalaction_exh_ko {
            get {
                return ResourceManager.GetString("generalaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	할로네
        ///2	메느피나
        ///3	살리아크
        ///4	니메이아
        ///5	리믈렌
        ///6	오쉬온
        ///7	비레고
        ///8	랄거
        ///9	아제마
        ///10	날달
        ///11	노피카
        ///12	알디크
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string guardiandeity_exh_ko {
            get {
                return ResourceManager.GetString("guardiandeity_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	@
        ///2	@
        ///3	@
        ///4	@
        ///5	@
        ///6	@
        ///7	@
        ///8	@
        ///9	@
        ///10	@
        ///11	@
        ///13	@
        ///14	@
        ///15	@
        ///16	@
        ///17	@
        ///18	@
        ///19	@
        ///20	@
        ///22	@
        ///23	@
        ///24	@
        ///25	@
        ///49	mount
        ///50	classjob
        ///51	placename
        ///52	race
        ///53	tribe
        ///54	guardiandeity
        ///55	generalaction
        ///56	action
        ///57	craftaction
        ///58	buddyAction
        ///59	petaction
        ///60	weather
        ///61	maincommand
        ///62	textcommand
        ///63	action
        ///64	pet
        ///65	companion
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0	
        ///1	무기 넣기/꺼내기
        ///2	내 캐릭터
        ///3	기술 목록
        ///4	퀘스트
        ///5	임무 정보 목록
        ///6	업적 목록
        ///7	채집수첩
        ///8	토벌수첩
        ///9	제작수첩
        ///10	소지품
        ///11	임무용 아이템 목록
        ///12	파티원
        ///13	친구 목록 관리
        ///14	차단 목록 관리
        ///15	플레이어 검색
        ///16	지도
        ///17	감정 표현
        ///18	대상 표식
        ///19	시스템 설정
        ///20	단축키 설정
        ///21	매크로 관리
        ///22	HUD 배열 변경
        ///23	접속 종료
        ///24	게임 종료
        ///25	장비함
        ///26	
        ///27	자유부대
        ///28	링크셸
        ///29	낚시수첩
        ///30	도움말
        ///31	추천 임무
        ///32	
        ///33	임무 찾기
        ///34	캐릭터 설정
        ///35	텔레포
        ///36	데존
        ///37	등급 및 라이선스 표시
        ///38	수첩
        ///39	플레이어 간 교류
        ///40	시스템
        ///41	어류도감
        ///42	버디
        ///43	임무
        ///44	하우징
        ///45	화면 설정
        ///46	소리 설정
        ///47	그래픽 설정
        ///48	마우스 설정
        ///49	&lt;if(PLYR: 76 ? 1 ) {컨트롤러 설정} else {게임패드 설정[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string maincommand_exh_ko {
            get {
                return ResourceManager.GetString("maincommand_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	내 초코보
        ///4	구부
        ///5	레거시 초코보
        ///6	마도 아머
        ///8	커얼
        ///9	아리만
        ///15	유니콘
        ///18	베히모스
        ///19	훈련된 도마뱀
        ///20	월계수 구부
        ///21	C식 마도 아머
        ///22	나이트메어
        ///25	뚱보 초코보
        ///26	훈련된 엘브스트
        ///27	봄 벌룬
        ///28	아이톤
        ///29	크산토스
        ///30	굴팍시
        ///31	엔바르
        ///32	전투사자
        ///33	전투곰
        ///34	그랑초코보
        ///35	다이어울프
        ///36	림사 로민사 군마
        ///37	그리다니아 군마
        ///38	울다하 군마
        ///40	마르카브
        ///41	영원초코보
        ///42	슬레이프니르
        ///43	보레아스
        ///44	행진대 초코보
        ///45	검은 초코보
        ///46	금강거북
        ///47	기린
        ///48	탑승 시스템
        ///49	펜리르
        ///50	미드가르드오름
        ///52	빨간 그랑초코보
        ///53	사누와
        ///54	그리핀
        ///55	마나커터
        ///56	전투흑표범
        ///58	고블린워커
        ///59	트윈타니아
        ///62	마녀의 빗자루
        ///67	페가수스
        ///68	리위아 전용 마도 아머
        ///69	네로 전용 마도 아머
        ///70	와이번
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mount_exh_ko {
            get {
                return ResourceManager.GetString("mount_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	카벙클 에메랄드
        ///2	카벙클 토파즈
        ///3	이프리트 에기
        ///4	타이탄 에기
        ///5	가루다 에기
        ///6	요정 에오스
        ///7	요정 셀레네
        ///8	자동포탑 룩
        ///9	자동포탑 비숍
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pet_exh_ko {
            get {
                return ResourceManager.GetString("pet_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	귀환
        ///2	추종
        ///3	이동
        ///4	대기
        ///5	공격
        ///6	평화
        ///7	자유 전투
        ///8	지시 전투
        ///9	돌풍
        ///10	날리기
        ///11	하강 기류
        ///12	에메랄드의 광휘
        ///13	할퀴기
        ///14	토파즈의 빛
        ///15	웅크리기
        ///16	몸통 박치기
        ///17	바람의 칼날
        ///18	충격파
        ///19	대기 난도질
        ///20	악화
        ///21	대기 폭발
        ///22	바위 쪼개기
        ///23	산 쪼개기
        ///24	대지의 수호
        ///25	산사태
        ///26	대지의 분노
        ///27	진홍 회오리
        ///28	불타는 일격
        ///29	광휘의 방패
        ///30	화염 작열
        ///31	지옥의 화염
        ///32	빛의 치유
        ///33	빛의 속삭임
        ///34	요정의 서약
        ///35	요정의 광휘
        ///36	빛의 치유
        ///37	빛의 침묵
        ///38	요정의 손길
        ///39	요정의 바람
        ///40	공격 지시
        ///41	보조 지시
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string petaction_exh_ko {
            get {
                return ResourceManager.GetString("petaction_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   18	길드 의뢰
        ///20	하이델린
        ///21	에오르제아
        ///22	라노시아
        ///23	검은장막 숲
        ///24	다날란
        ///25	커르다스
        ///26	모르도나
        ///27	림사 로민사
        ///28	림사 로민사 상층 갑판
        ///29	림사 로민사 하층 갑판
        ///30	중부 라노시아
        ///31	저지 라노시아
        ///32	동부 라노시아
        ///33	서부 라노시아
        ///34	고지 라노시아
        ///35	사스타샤 침식 동굴
        ///36	브레이플록스의 야영지
        ///37	방랑자의 궁전
        ///39	그리다니아
        ///40	울다하 날 회랑
        ///41	울다하 달 회랑
        ///42	서부 다날란
        ///43	중부 다날란
        ///44	동부 다날란
        ///45	남부 다날란
        ///46	북부 다날란
        ///47	나무꾼의 비명
        ///48	구리종 광산
        ///49	할라탈리 수련장
        ///50	카른의 무너진 사원
        ///51	울다하
        ///52	그리다니아 신시가지
        ///53	그리다니아 구시가지
        ///54	검은장막 숲 중부삼림
        ///55	검은장막 숲 동부삼림
        ///56	검은장막 숲 남부삼림
        ///57	검은장막 숲 북부삼림
        ///58	탐타라 묘소
        ///59	하우케타 별궁
        ///61	토토라크 감옥
        ///62	이슈가르드
        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string placename_exh_ko {
            get {
                return ResourceManager.GetString("placename_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	휴런
        ///2	엘레젠
        ///3	라라펠
        ///4	미코테
        ///5	루가딘
        ///6	아우라
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string race_exh_ko {
            get {
                return ResourceManager.GetString("race_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index	7 [0x0][0x0]
        ///102	/말
        ///103	/외
        ///104	/귓
        ///105	/파
        ///106	/링
        ///107	/링1
        ///108	/링2
        ///109	/링3
        ///110	/링4
        ///111	/링5
        ///112	/링6
        ///113	/링7
        ///114	/링8
        ///115	/자
        ///116	/혼
        ///117	/떠
        ///118	/대답
        ///119	/연
        ///121	/참가
        ///122	/거절
        ///123	/초대
        ///124	/추방
        ///125	/파티장
        ///126	/탈퇴
        ///131	/조사
        ///132	/거래
        ///133	/자동달리기
        ///134	/따라가기
        ///135	/전리품
        ///136	/마테리아요청
        ///141	/캐릭터
        ///142	/퀘스트
        ///143	/임무찾기
        ///144	/장비함
        ///145	/토벌수첩
        ///146	/제작수첩
        ///147	/채집수첩
        ///148	/낚시수첩
        ///149	/업적
        ///150	/파티명령
        ///151	/친구목록
        ///152	/차단목록
        ///153	/플레이어검색
        ///154	/지도
        ///155	/텔레포
        ///156	/표식지정
        ///157	/기술목록
        ///158	/임무대기
        ///159	/추천임무
        ///160	/소지품
        ///161	/자유[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string textcommand_exh_ko {
            get {
                return ResourceManager.GetString("textcommand_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	중원 부족
        ///2	고원 부족
        ///3	숲 부족
        ///4	황혼 부족
        ///5	평원 부족
        ///6	사막 부족
        ///7	태양의 추종자
        ///8	달의 수호자
        ///9	바다늑대
        ///10	불꽃지킴이
        ///11	아우라 렌
        ///12	아우라 젤라
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tribe_exh_ko {
            get {
                return ResourceManager.GetString("tribe_exh_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	쾌청
        ///2	맑음
        ///3	흐림
        ///4	안개
        ///5	바람
        ///6	강풍
        ///7	비
        ///8	폭우
        ///9	번개
        ///10	뇌우
        ///11	모래먼지
        ///12	모래폭풍
        ///13	열파
        ///14	작열파
        ///15	눈
        ///16	눈보라
        ///17	요마의 안개
        ///18	오로라
        ///19	어둠
        ///20	투기
        ///21	흐림
        ///22	뇌운
        ///23	파랑
        ///24	파랑
        ///25	먹구름
        ///26	작열파
        ///27	요마의 안개
        ///28	강풍
        ///29	분화
        ///30	맑음
        ///31	맑음
        ///32	맑음
        ///33	맑음
        ///34	맑음
        ///35	극광
        ///36	용핵
        ///37	용핵
        ///38	용핵
        ///39	용핵
        ///40	떼구름
        ///41	떼구름
        ///42	떼구름
        ///43	떼구름
        ///44	섭리
        ///45	섭리
        ///46	섭리
        ///47	섭리
        ///48	섭리
        ///49	그림자바람
        ///50	방전
        ///51	연무
        ///52	맑음
        ///53	야수번개
        ///54	번개파동
        ///55	야수번개
        ///56	섭리
        ///57	번개
        ///58	번개
        ///59	
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string weather_exh_ko {
            get {
                return ResourceManager.GetString("weather_exh_ko", resourceCulture);
            }
        }
    }
}
